#!/bin/sh
set -e

. /usr/local/share/pick.sh

set_timezone() {
	local auto_timezone="$(wget -q -O- 'http://ip-api.com/line/?fields=timezone')"
	local auto_continent="$(printf "$auto_timezone" | cut -d / -f1)"
	local auto_city="$(printf "$auto_timezone" | cut -d / -f2)"
	
	pick continent "$(ls -1 -d /usr/share/zoneinfo/*/ | cut -d / -f5)" $auto_continent
	pick city "$(ls -1 /usr/share/zoneinfo/"$continent"/* | cut -d / -f6)" $auto_city
	tzset "${continent}/${city}"
}

manage_packages() {
	echo 'packages:'
	pick mode 'update\ninstall\nremove'
	[ "$mode" = install ] && {
		printf 'search for: '
		read -r search_entry
		pick package_name "$(apk search "$search_entry")"
		package_name="$(echo "$package_name" | { read first _rest; echo $first; })"
	}
	[ "$mode" = remove ] && {
		printf 'search for: '
		read -r search_entry
		pick package_name "$(apk search "$search_entry")"
		package_name="$(echo "$package_name" | { read first _rest; echo $first; })"
		printf "remove $package_name (y/N)? "
		read -r answer
		[ "$answer" = y ] || exit
	}
	system-packages "$mode" "$package_name"
}

pick selected_option "timezone\nconnections\nlanguage\npackages"
case "$selected_option" in
	timezone) set_timezone ;;
	connections) . /usr/local/share/system-connections.sh ;;
	packages) manage_packages ;;
esac
