#!/bin/sh -e

# wlan
# https://iwd.wiki.kernel.org/
wlan () {
  if [ "$1" = "forget" ]; then
    iwctl known-networks list
    echo -n "select the network to forget: "; read ssid
    iwctl known-networks "$ssid" forget
    exit
  fi
  iwctl device list
  echo -n "select a device: "; read device
  rfkill unblock wlan
  iwctl station "$device" scan
  iwctl station "$device" get-networks
  echo -n "select a network: "; read ssid
  iwctl station "$device" connect "$ssid"
}

# wifi access point
# https://iwd.wiki.kernel.org/ap_mode
# https://man.archlinux.org/man/community/iwd/iwd.ap.5.en
# https://wiki.archlinux.org/title/software_access_point
# https://hackaday.io/project/162164/instructions?page=2
# https://raspberrypi.stackexchange.com/questions/133403/configure-usb-wi-fi-dongle-as-stand-alone-access-point-with-systemd-networkd

# internet sharing
# https://dabase.com/blog/2012/Sharing_an_Internet_connection_in_Archlinux/
# https://wiki.archlinux.org/title/Router
# https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#veth
# https://man.archlinux.org/man/core/systemd/systemd.netdev.5.en
# https://man.archlinux.org/man/core/systemd/systemd.network.5.en

# https://en.wikipedia.org/wiki/Network_access_server
# https://en.wikipedia.org/wiki/Captive_portal

# https://wiki.archlinux.org/title/Mobile_broadband_modem
# https://man.archlinux.org/man/extra/modemmanager/mmcli.1.en
# https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/configs/releng/airootfs/etc/systemd/network/20-wwan.network
# https://github.com/systemd/systemd/issues/20370

# https://wiki.archlinux.org/title/Direct_modem_connection#DSL_(PPPoE)
# https://github.com/dfskoll/rp-pppoe/blob/master/doc/HOW-TO-CONNECT

case "$1" in
  wlan) shift; wlan "$@" ;;
esac
