#!/bin/sh
set -e

manage_wifi() {
	local mode="$(printf "connect\nremove" | fzy)" device= ssid=
	
	if [ "$mode" = connect ]; then
		echo 'select a device:'
		device="$(iwctl device list | fzy | { read first _; echo $first; })"
		
		iwctl station "$device" scan
		echo 'select a network to connect:'
		ssid="$(iwctl station "$device" get-networks | fzy | cut -c5- | cut -d ' ' -f1)"
		iwctl station "$device" connect "$ssid"
	fi
	
	if [ "$mode" = remove ]; then
		echo 'select a network to remove:'
		ssid="$(iwctl known-networks list | fzy | cut -c5- | cut -d ' ' -f1)"
		
		printf "remove \"$ssid\" (y/N)? "
		read -r answer
		[ "$answer" = y ] || exit
		
		iwctl known-networks "$ssid" forget
	fi
}

manage_cell() {
	echo "not yet implemented"
}

manage_bluetooth() {
	local mode= device=
	
	echo "not yet implemented"; exit
	# https://forum.endeavouros.com/t/how-to-script-bluetoothctl-commands/18225/10
	# https://gist.github.com/RamonGilabert/046727b302b4d9fb0055
	# "echo '' | ..." or expect
	#
	# https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/test/simple-agent
	# https://ukbaz.github.io/howto/python_gio_1.html
	# https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt
	
	mode="$(printf "add\nremove" | fzy)"
	
	if [ "$mode" = remove ]; then
		bluetoothctl scan on &
		sleep 3
		echo "select a device:"
		device="$(bluetoothctl devices | fzy | { read _first mac_address; echo $mac_address; })"
		
		if bluetoothctl --agent -- pair "$device"; then
			bluetoothctl trust "$device"
			bluetoothctl connect "$device"
		else
			bluetoothctl untrust "$device"
		fi
	fi
	
	if [ "$mode" = remove ]; then
		echo "select a device:"
		device="$(bluetoothctl devices | fzy | { read _first mac_address; echo $mac_address; })"
		bluetoothctl disconnect "$device"
		bluetoothctl untrust "$device"
	fi
}

manage_radio_devices() {
	# wifi, cellular, bluetooth, gps
	local lines="all\n$(rfkill -n -o "TYPE,SOFT,HARD")" device= action=
	echo 'select a radio device:'
	device="$(printf "$lines" | fzy | cut -d " " -f1)"

	action="$(printf "block\nunblock" | fzy)"
	rfkill "$action" "$device"
}

manage_router() {
	echo "not yet implemented"
	
	# https://wiki.archlinux.org/title/Router
	# https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#veth
	
	# ask for add/remove
	# if remove:
	# , show the out devices
	# , ask for the name of devices (or all)
	# , remove the devices from ifupdown-ng config, and from Connman unmanaged
	# if add:
	# , ask for the name of devices to add
	# , put the devices in connman unmanaged
	# , install busybox-extras (for udhcpd)
	# , run a dhcp server on them, using ifupdown-ng (https://github.com/ifupdown-ng/ifupdown-ng/tree/main/doc)
	
	# if the device is a wireless LAN (ie we want a wifi access point)
	# if there is only one wifi device, create a virtual one (concurrent AP-STA mode)
	# https://wiki.archlinux.org/title/software_access_point
	# https://variwiki.com/index.php?title=Wifi_NetworkManager#WiFi_STA.2FAP_concurrency
	# activate AP mode on it, using iwd
	# http://blog.hoxnox.com/gentoo/wifi-hotspot.html
	# https://wiki.alpinelinux.org/wiki/Wireless_AP_with_udhcpd_and_NAT
	# when removing a wireless device, disable AP mode, and delete the virtual device (if any)
	
	#echo -n '[Match]
	#Type=wlan
	#WLANInterfaceType=ap
	#[Network]
	#Address=0.0.0.0/24
	#DHCPServer=yes
	#IPMasquerade=both
	#' > /etc/systemd/network/80-wifi-ap.network
	# https://hackaday.io/project/162164/instructions?page=2
	# https://raspberrypi.stackexchange.com/questions/133403/configure-usb-wi-fi-dongle-as-stand-alone-access-point-with-systemd-networkd
	# https://man.archlinux.org/man/core/systemd/systemd.netdev.5.en
}

manage_connections() {
	local selected_option="$(printf "wifi\ncellular\nbluetooth\nradio\nrouter" | fzy)"
	case "$selected_option" in
		wifi) manage_wifi ;;
		cellular) manage_cell ;;
		bluetooth) manage_bluetooth ;;
		radio) manage_radio_devices ;;
		router) manage_router ;;
	esac
}

set_timezone() {
	# guess the timezone, but let the user to confirm it
	local geoip_tz="$(wget -q -O- 'http://ip-api.com/line/?fields=timezone')"
	local geoip_tz_continent="$(printf "$geoip_tz" | cut -d / -f1)"
	local geoip_tz_city="$(printf "$geoip_tz" | cut -d / -f2)"
	local continent="$(ls -1 -d /usr/share/zoneinfo/*/ | cut -d / -f5 | fzy -q "$geoip_tz_continent")"
	local city="$(ls -1 /usr/share/zoneinfo/"$continent"/* | cut -d / -f6 | fzy -q "$geoip_tz_city")"
	timedatectl set-timezone "${continent}/${city}"
}

manage_packages() {
	local mode= package_name= answer=n
	echo 'packages:'
	mode="$(printf "update\ninstall\nremove" | fzy)"
	
	[ "$mode" = install ] && {
		printf 'search for: '
		read -r search_entry
		pkexec apt-get update
		package_name="$(apt-cache search "$search_entry" | fzy | { read first _rest; echo $first; })"
		apt-cache show "$package_name"
		printf "install $package_name (Y/n)? "
		read -r answer
		[ "$answer" = n ] && exit
	}
	
	[ "$mode" = remove ] && {
		printf 'search for: '
		read -r search_entry
		package_name="$(apt-cache search "$search_entry" | fzy | { read first _rest; echo $first; })"
		printf "remove $package_name (y/N)? "
		read -r answer
		[ "$answer" = y ] || exit
	}
	
	sudo /usr/local/bin/system-packages "$mode" "$package_name"
}

selected_option="$(printf "timezone\nconnections\npackages" | fzy)"
case "$selected_option" in
	connections) manage_connections ;;
	timezone) set_timezone ;;
	packages) manage_packages ;;
esac
