#!/bin/sh

# https://github.com/cmuench/pacman-auto-update/blob/master/root/usr/lib/pacman-auto-update/pacman-auto-update

# exit if "/usr/local/bin/arch" has more than one instances
if [[ $(pgrep -c /usr/local/bin/arch) -gt 1 ]]; then
  echo 'another instance is running;'
  exit
fi

# remove orphan lock
if [[ -f /var/lib/pacman/db.lck && $(pgrep -c /usr/local/bin/arch) == 0 ]]; then
  rm /var/lib/pacman/db.lck
fi

batteryIsEmpty() {
  local capacity="/sys/class/power_supply/BAT1/capacity"
	[[ -f "${capacity}" && "$(cat "${capacity}")" -le 20 ]]
}
connectionIsMetered() {
	nmcli --terse --fields GENERAL.METERED dev show | grep --quiet "yes"
}
if [[ "$1" == "autoupdate" && ( $(batteryIsEmpty) || $(connectionIsMetered) ) ]]; then
  exit
fi

if [[ -d /subvols/1 ]]; then
  btrfs subvolume delete /subvols/1
fi

if [[ "$1" == "del" ]]; then
  primaryPackages=" base grub intel-ucode amd-ucode linux linux-firmware reflector networkmanager gnome-shell gdm gvfs gnome-terminal "
  for p in "${@:2}"; do
    if [[ "$primaryPackages" == *" $p "* ]]; then
      echo "can't remove primary packages; try this instead:"
      echo 'pkexec pacman -Rns package_names'
      exit
    fi
  done

  pacman -Rns ${@:2}
  # if "/" is not "/subvols/0":
  if [[ ! "/" -ef "/subvols/0" ]]; then
    arch-chroot /subvols/0 "pacman --noconfirm -Rns -- ${@:2}"
  fi
  exit
fi

if [[ "$1" != "update" && "$1" != "autoupdate" && "$1" != "add" ]]; then
  echo 'usage:
  arch add package_names
  arch remove package_names
  arch update'
  exit
fi

set -e

# create a snapshot of "/subvols/0" in "/subvols/1"
btrfs subvolume snapshot /subvols/0 /subvols/1

mount --bind /etc /subvols/1/etc
mount --bind /home /subvols/1/home
mount --bind /root /subvols/1/root
mount --bind /opt /subvols/1/opt
mount --bind /usr/local /subvols/1/usr/local
mount --bind /srv /subvols/1/srv
mount --bind /tmp /subvols/1/tmp
mount --bind /var /subvols/1/var
mount --bind /boot/efi /subvols/1/boot/efi

arch-chroot /subvols/1 /usr/bin/bash << EOF
set -e
if [[ "$1" == "autoupdate" ]]; then
  pacman -Syu --noconfirm
else
  pacman -Syu -- ${@:2}
fi
# clear orphaned packages:
pacman -Qttdq | pacman --noconfirm -Rns - 2>/dev/null
# clear cache:
pacman --noconfirm -Sc
EOF

mv /subvols/1 /subvols/0
