#!env python3

from gi.repository import Gio, GLib

connection = Gio.DBus.system

image_path=
device_name=

# if the device mounted, unmount it

# http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.OpenDevice
#"org.freedesktop.UDisks2"
#"/org/freedesktop/UDisks2/block_devices/"+device_name
#org.freedesktop.UDisks2.Block
#OpenDevice
#'w'
#['O_EXCL','O_SYNC','O_CLOEXEC']
#fd
# read from image_path, write into fd
