#!pkexec /bin/sh
set -e

mode="$1"
package_name="$2"

[ -f /tmp/apm-lock ] && {
  echo 'another instance is running; wait for it to finish, or reboot the system'
  exit 1
}
trap "rm -f /tmp/apm-lock; trap - EXIT; exit" EXIT HUP INT QUIT ABRT TERM
touch /tmp/apm-lock

[ "$mode" = "install-firmware" ] && {
  device_name="$2"
  # find and install required firmwares
  # https://salsa.debian.org/debian/isenkram
  exit
}

if [ "$mode" = "autoupdate" ]; then
  critical_battery() {
    battery_capacity="/sys/class/power_supply/BAT0/capacity"
    [ -f "$battery_capacity" ] || battery_capacity="/sys/class/power_supply/BAT1/capacity"
  	[ -f "$battery_capacity" ] && [ "$(cat "$battery_capacity")" -le 20 ]
  }
  
  metered_connection() {
    active_net_device="$(ip route show default | head -1 | sed -n 's/.* dev \([^\ ]*\) .*/\1/p')"
    is_metered=false
  	case "$active_net_device" in
      ww*) is_metered=true ;;
    esac
    # todo: DHCP option 43 ANDROID_METERED
    is_metered
  }
  
  critical_battery || metered_connection && exit 0
fi

old_snapshot="$(realpath /0)"
if [ "$old_snapshot" = "/1" ]; then
  new_snapshot="/2"
else
  new_snapshot="/1"
fi

[ -d "$new_snapshot" ] && btrfs subvolume delete "$new_snapshot"

btrfs subvolume create "$new_snapshot"
btrfs subvolume snapshot "$old_snapshot" "$new_snapshot"

mount --bind /etc "$new_snapshot"/etc
mount --bind /home "$new_snapshot"/home
mount --bind /root "$new_snapshot"/root
mount --bind /opt "$new_snapshot"/opt
mount --bind /usr/local "$new_snapshot"/usr/local
mount --bind /srv "$new_snapshot"/srv
mount --bind /tmp "$new_snapshot"/tmp
mount --bind /var "$new_snapshot"/var
mount --bind /boot/efi "$new_snapshot"/boot/efi

chroot "$new_snapshot" /usr/bin/sh -c 'set -e
case "$1" in
  autoupdate) apt-get update --yes; apt-get dist-upgrade --yes ;;
  update) apt-get update; apt-get dist-upgrade ;;
  install) apt-get install --no-install-recommends -- "$2" ;;
  remove) apt-get purge -- "$2" ;;
esac
apt-get autoremove --purge --yes
apt-get autoclean --yes
bootctl update --graceful --quiet --no-variables --esp-path=/boot/efi' apm "$mode" "$package_name"

ln --symbolic --force -T "$new_snapshot" /3
mv --force -T /3 /0
